language: java
dist: trusty
jdk: oraclejdk8
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api-key:
    secure: uSdT0uxujJm/Q2sPo62fsZ8jptdTrrS7XtuUaJ5Q8iBYedh5FIYmiqASHWZoY55mkMVE+As2Hb9swmaiisywxIfpn7Gf9DOcUozpRkZEthD/6VXdNSJpTc+hODikEEQ0WwC15DCAAyLXT7tEM97fJxlLaHRMFJYj5fmLX29SN1vJvu2ipn17ANGYXsz58QDRmxTKBWTlG7vNwLsa3/ToAokO31mJ/SrqCtZhUvNWUocCoTqDCITJyQJwYkRsrKmQWm0kEYtnl7nZJTZ8nXT5CgLxU2lO3iP7zMRWNp6NewlH8e1imSpNXq6+3+VudPWgPceyVzOa8+bEDz4m4bdVHOrca0FT8NiRV9tz2isybgTu3wgZ/F/EOiTOoTc8EIKxixeZjR5m9k/cxOUWFK7xCej8fdZf3PFw65eN2tCDjjSazoAJRYmFG5MooqZlPXQZtVnvRIhYOxlsKTvMi1SOc6evPayBqt5JcBYv0YmlfF2Xs0den6Xy0P8TzDvLtVCJOejXIEpUUMK+RCQ7vVZiKacWGBIrIjwTxqY1DP9QHzZIsswOInIoQrBD+b/9pvhvu8ocIBikuUywz2gwx0CDSdM3ukdNfIHcU91Vv27syGxcKJ+cRR8orvqSskx5GNDRHa0i5II+Atib9Cs9hejiCs6EAFXmdjn0oz008QDzrCQ=
  app: app-calculator-zyg