language: java
dist: trusty
jdk: oraclejdk8

script:
- ./mvnw clean install -B

deploy:
  provider: heroku
  api-key: R/XmwzaD2CWSLtxNVUm7xN4Hn502yYsjgR64hqKmHACUDT15nEHUgADKxwuMSV85OAQ6KU9xiaIcKX/3qVhi5siOXbxLpXOgrn2AR5wtu2LH9kxFjpSlh7vC32DmprXSb90zFY0C3RvfjA+9kplSer6CFREZXYcK054Zz7Y86eXV43SRg3UWuE/hERwg1TtGmF5OVEmEKAN83vVB1spa2MHYv3eQqhc6C8g9xwUjCa1EinQCLb95m831D6kmJ54ovFTNIIuoh1gvczkfbVj6gdD0uB8muNl8MPBswHWzEb87wF1qq9zvylVnlLbRNFgrkSUGQ6gSiTm/3s8qOL1vc6Y23GoY05K7YqMVSh3FxLw/IyfZfirrNEBJ/Z6GxJN3c8D4UViGSGMQYu9HHOfYDumfoQyyQtZ4WAe7fj52mtRhOqFwbE7GZM7QHOM+AZcUwa35hoqUlvgtXLN8fP4ZYPNuPRZRJ8IvTBQlQf/IkHSN1K84E4jJW/4ywZlLwtQU7J/HAk5qSVEKOy1w655sM/xIoHLG8LVvRZ5n7kTMEgDDJjZO0NzjG6IoCA85zjYavKN8+6Y7ODz3phs0nVgZEVsfjZhyr9cwNMhFY/oE3mss93G8JfrUCabLCMCo5Dz4duSFQUw7ee455tEj7LSfIdfipKn5xDkAGsGtCvufhH0=
  app: app-calculator-zyg