language: java
dist: trusty
jdk: oraclejdk8
before_install:
- chmod +x mvnw
script:
- "./mvnw clean install -B"
deploy:
  provider: heroku
  api-key:
    secure: txdtnKsHis9I8v+8eyL8bMRKUXgfrjWT3GjHVBeErV1cgXVU5+k2ZG2Bk0NvRC7fOAknFsZVQYe2+Rimd6yvLfbZzZxWDLPQRGtv9NnofzHvIHkjzi93L9ihCW8W8b90UpL5SDYdaE2AVT1RUMV4jY0fqaPrfGeO0lxND7AAiFdHu0NCBK1ceeoMZqlXyrHDkkgBI0EDAH/5hs1U2vRpQiCzxpinjA6PsAfaaiaaiMeMRQ+w9O4ocUgK2VLz7jyaWKNSZnnk65q0HNmlWGbnTq1fLIioaZaoLUlC/RbtTVPAIVjTqdmIJQT2F6o1YgV+9Jn0av10xN4tLldti77MB/bHk6HAVKF3699HSMfJmczaUk4HjAhArFflCQrs/5gTQXNwVM0zS6RUWWAQgNvJ7leiddTU1c8ffqF1n4zF1N8Mo+rs1F6SWs9zca0UO2w2P3E+s9fKBUhM6tc+X6aQzMFtGZRdHsRgfpaYL3xOH/aIl6bhUiWvqZEuGTd1bXuKxbnxL1amjDdvyk7lksVELcpqZKU/fKNE8pIl3Uf7i5QuyiN23n6tRvlN4bCcsIRHQfIjdkv00beYdhSjASN0LSWG5TJS9zQFMFJKT2HtU+7t5xK/mSwM9un4vUIsers3Ls4nnp9y1Kjp094Z6PC4isM59w0Bosv5A1WcPPypT24=
  app: app-calculator-zyg